apiVersion: v1
kind: Service
metadata:
  labels:
    name: nexus3
  name: nexus3
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    name: nexus3