apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nexus3
  name: nexus-controller
spec:
  replicas: 1
  selector:
    name: nexus3
  template:
    metadata:
      labels:
        name: nexus3
    spec:
      containers:
      - image: kolov/nexus3:latest
        name: nexus
        ports:
        - containerPort: 8081
          name: nexus-server
        volumeMounts:
          - name: nexus-repo
            mountPath: /nexus-data
      volumes:
        - name: nexus-repo
          gcePersistentDisk:
            pdName: nexus-repo
            fsType: ext4
