apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: postgre5
    sonar-version: v4
  name: postgre5
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgre5
    spec:
      containers:
      - image: orchardup/postgresql:latest
        name: postgre
        env:
          - name: POSTGRESQL_USER
            value: sonar
          - name: POSTGRESQL_PASS
            value: xaexohquaetiesoo
          - name: POSTGRESQL_DB
            value: sonar
        volumeMounts:
            - name: postgre-sonar5-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgre-sonar5-storage
          hostPath:
            path: /var/data/docker/postgre-sonar5
