apiVersion: v1
kind: Service
metadata:
  name: sonar
  labels:
    name: sonar
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: sonar