apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sonar
  name: sonar-controller
spec:
  replicas: 1
  selector:
    name: sonar
  template:
    metadata:
      labels:
        name: sonar
    spec:
      containers:
      - image: sonarqube
        name: sonar
        env:
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://postgre/sonar
          - name: SONARQUBE_JDBC_USERNAME
            value: sonar
          - name: SONARQUBE_JDBC_PASSWORD
            value: xaexohquaetiesoo
          - name: DB_NAME
            value: sonar
        ports:
        - containerPort: 9000
          name: sonar-server
