apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar4
  name: sonar4
spec:
  type: LoadBalancer
  ports:
    - port: 9004
      targetPort: 9000
      protocol: TCP
  selector:
    name: sonar4








