apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sonar5
    sonar-version: v5
  name: sonar5
spec:
  replicas: 1
  selector:
    name: sonar5
  template:
    metadata:
      labels:
        name: sonar5
    spec:
      containers:
      - image: sonarqube
        name: sonar5
        env:
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://postgre5/sonar
          - name: SONARQUBE_JDBC_USERNAME
            value: sonar
          - name: SONARQUBE_JDBC_PASSWORD
            value: xaexohquaetiesoo
          - name: DB_NAME
            value: sonar
        ports:
        - containerPort: 9000
          name: sonar5-server
