apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.200
  ports:
    - port: 9004
      targetPort: 9000
      protocol: TCP
  selector:
    name: sonar
