apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar5
  name: sonar5
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.200
  ports:
    - port: 9005
      targetPort: 9000
      protocol: TCP
  selector:
    name: sonar5








