apiVersion: v1
kind: ReplicationController
metadata:
  name: sonar4
spec:
  replicas: 1
  selector:
    name: sonar4
  template:
    metadata:
      labels:
        name: sonar4
    spec:
      containers:
      - image: sonarqube:4.5.7
        name: sonar4
        env:
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://postgre4/sonar
          - name: SONARQUBE_JDBC_USERNAME
            value: sonar
          - name: SONARQUBE_JDBC_PASSWORD
            value: xaexohquaetiesoo
          - name: DB_NAME
            value: sonar
        ports:
        - containerPort: 9000
          name: sonar4
