apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: wcig
  name: wcig-controller
spec:
  replicas: 1
  selector:
    name: wcig
  template:
    metadata:
      labels:
        name: wcig
    spec:
      containers:
      - image: eu.gcr.io/wherecanigonow/wcig
        name: wcig
        ports:
        - containerPort: 3000
          name: wcig-server
