apiVersion: v1
kind: Service
metadata:
  labels:
    name: jenkins2
  name: jenkins2
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: jenkins2